export const config = {
  PORT : 5500,
  MONGODB_URL : '',   
  SECRET : '',  
  JWT_ACCESS_SECRET : '',
  JWT_REFRESH_SECRET : '',
  HOST_EMAIL : '',
  PORT_EMAIL : '',
  USER_EMAIL : '',
  PASSWORD_EMAIL : '',
  FEEDBACK_EMAIL : '',
  COMPLAIN_EMAIL : '[]',
  SUBJECT : 'Сообщение с портала АМП',
  CORS_DOMAINS:'http://localhost:3000, http://localhost:3001, http://localhost:5173',
  NEWS_LIMIT: '17',
  PARTNER_LIMIT: '12',
  DRAFT_LIMIT:'12',
  PLANT_LIMIT:'12',
  DESTINATION_NEWS:'news',
  DESTINATION_USER_AMP:'logo',
  DESTINATION_PLANT_GROUP:'plant_group',
  DESTINATION_PLANT:'plant',
  DESTINATION_PLANT_MAIN_AP:'plant_main_ap',
  DESTINATION_PLANT_GROUP_AP:'plant_group_ap',
  DESTINATION_PLANT_AP:'plant_ap',
  DESTINATION_SEND_ZVK: 'send_zvk',
  DESTINATION_AD: 'ad',
  ZNAK: '★',
  ZNAK2: '☆',
  ALL_STARS_COUNT: 5,
  TTOKEN: '',
  CHATID: '',
  UPLOAD_API_URL:'',
  CLIENT_URL:'',
};
